# -*- coding: utf-8 -*-
"""yolo_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrYlRtiui_vwnhd7_GkiS5dubuoxhiPz
"""

nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

pip install ultralytics

from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()

pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="secret_key")
project = rf.workspace("caio-ygfyx").project("placass")
version = project.version(1)
dataset = version.download("yolov8")

yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=150 imgsz=640

Image(filename=f'/content/runs/detect/train/confusion_matrix.png', width=600)

Image(filename=f'/content/runs/detect/train/results.png', width=600)

yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.5 source={dataset.location}/test/images

import glob
from IPython.display import Image, display

for imPath in glob.glob('/content/runs/detect/predict/*.jpg')[:3]:
  display(Image(filename=imPath))
  print("\n")

import shutil

shutil.make_archive('/content/model_trained', 'zip', '/content/runs/detect/train/')